version: '3'

services:
    serverless-api:
        build:
            context: ./docker/serverless
        volumes:
            - ./:/home/serverless
        ports:
            - "3000:3000"
        links:
            - "database:database"
    
    database:
        image: mysql
        restart: always
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        ports:
            - "3306:3306"
        expose:
            - "3306"